"""Initial

Revision ID: ea4e1da7957b
Revises: 
Create Date: 2023-04-13 18:54:53.925216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4e1da7957b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertise',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=320), nullable=False),
                    sa.Column('address', sa.String(length=500), nullable=False),
                    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('image_url', sa.String(length=320), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=320), nullable=False),
                    sa.Column('permissions', sa.String(length=320), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=320), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('advertise')
    # ### end Alembic commands ###
